spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://what-was-it-rds.cjnhnl3rox8c.ap-northeast-2.rds.amazonaws.com:3306/what_was_it
    username: admin
    password: memory1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

logging:
  level:
    org.hibernate.SQL: debug